### ISSUE TITLE
Broken Translation on FAQ page

### ISSUE THREAD

**Issue by ashadle** [Chia-Network/website#107]
All of the translations on the FAQ page are broken.

**Comment by dkackman** [comment]
@ashadle looks like the div that hosts the translated converted markdown's html got dropped from the html. fix incoming.

**Comment by dkackman** [comment]
Trying to style the english version of the FAQ directly in the html won't work and in this case broke the code that loads the FAQ markdown and transforms it via javascript. That html will always be replaced by the transformed markdown. If the resulting html needs to be styled we'll need to explore options in [Showdown.js](https://github.com/showdownjs/showdown) or come up with a different FAQ translation mechanism.
