### ISSUE TITLE
Mobile responsive on site

### ISSUE THREAD

**Issue by ashadle** [Chia-Network/website#109]
The majority of the site isn't mobile responsive - or it doesn't look very good on mobile.

**Comment by eldain** [comment]
I'd like to put some work into this starting with the navigation, but would like to add in a CSS preprocessor first as mentioned in #49 . Leaning towards using [this approach](https://github.com/hellobrian/sass-recipes/tree/master/node-sass). Thoughts beforehand? @ashadle
