### ISSUE TITLE
FAQ could use some contrast.

### ISSUE THREAD

**Issue by esques** [Chia-Network/website#133]
explanation: http://contrastrebellion.com
or TLDR: life is to short for grayish texts, help the elderly.

**Comment by ashadle** [comment]
Hey @rolandkofler I agree. It looks like the old styling was reverted. It should look like the attached. 
<img width="939" alt="screen shot 2018-03-26 at 4 44 39 pm" src="https://user-images.githubusercontent.com/13398595/37938917-0169902a-3115-11e8-82e7-a7f361a8640a.png">

**Comment by pwindle** [comment]
Piqued my interest so I went down the rabbit hole. w3c recommend:
7.0:1 contrast ratio for people with low vision (20/80 vision)
4.5:1 contrast ratio for normal text
3.0:1 contrast ratio for large, bold text

Some quick calculations for Arial typeface using [_these resources from the w3c_](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html#visual-audio-contrast-contrast-resources-head)):
contrast ratio thresholds for background colour #FFFFFF (white):
7.0:1 = #595959
4.5:1 = #767676
3.0:1 = #949494

Contrast ratio thresholds for background colour #374641 (dark green colour used in footer):
7.0:1 = #D8D8D8
4.5:1 = #AFAFAF
3.0:1 = #8E8E8E

A lot of text on the site is below the recommended minimum 3.0 contrast ratio, for example:
Paragraph text uses #939896 on #FFFFFF = 2.9:1
News page title uses #B0B0B0 on #FAFAFA = 2.1:1
FAQ text uses #B0B5B3 on #FFFFFF = 2.1:1

I've adjusted some colors and will submit a pull request.

**Comment by ashadle** [comment]
@pwindle interesting! Thanks, I just merged your pull request.
