### ISSUE TITLE
Translate website into Chinese

### ISSUE THREAD

**Issue by sportshark** [Chia-Network/website#137]
China is a big market，Chia is a great project.I can translate website into Chinese,What should I do?

**Comment by pwindle** [comment]
There used to be zh-CN chinese translations. Then they were removed around commit 03afd9992242a1e63a521f173fdf7557d9ae4a31
@ashadle ?

**Comment by ashadle** [comment]
Hi There, thank you so much for submitting this PR. We are rebranding the website and will have updated copy so I'm going to close out this ticket. Thank you!
