### ISSUE TITLE
Forward www.chia.net to https://chia.net

### ISSUE THREAD

**Issue by ashadle** [Chia-Network/website#153]
Currently it defaults to a page error.

**Comment by dkackman** [comment]
In order to do so someone who can edit your hosting environment needs to add the following to .htaccess file:

```
RewriteEngine On 
RewriteCond %{SERVER_PORT} 80 
RewriteRule ^(.*)$ https://chia.net/$1 [R=301,L]
```

You should also set the [HSTS header](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) in the server config.

**Comment by ashadle** [comment]
Hi There, thank you so much for submitting this PR. We are rebranding the website and will have updated copy so I'm going to close out this ticket. Thank you!
