### ISSUE TITLE
Update repo to new website 

### ISSUE THREAD

**Issue by EvanWinget** [Chia-Network/website#166]
Hello - just wondering if you planned on updating this repo since the new website launched so that users can add translations and make other PRs where applicable. Thanks!

**Comment by wjblanke** [comment]
The repo for the new website is at

https://github.com/Chia-Network/chia-network.github.io

Thanks for offering to contribute!

**Comment by EvanWinget** [comment]
Thanks for the link and sorry that I missed it!
