### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by maliky** [Chia-Network/website#3]
Hi,
I've translated your index.html to french.  how do I share it with you ?

**Comment by DatDraggy** [comment]
I don't think there is a way (yet). 

> Internationalization (This being a static site I'm not sure what best practices are for supporting multiple languages. Suggestions welcome.)

As said in the email, there is no way to do so yet. Maybe put it in a pastebin.org for now so that it can be integrated later.

**Comment by dkackman** [comment]
> Internationalization (This being a static site I'm not sure what best practices are for supporting multiple languages. Suggestions welcome.)

Mozilla has a framework. http://l20n.org/

It would require some structural changes to the site in order to separate and control translatable content. I might have some time to give it a go in the next few days, if no one else picks up that task.

**Comment by lbenevento** [comment]
Why don't you use a simple redirect feature? Like the main index page in English and through a localization system you can redirect users to the index page of their language. 
EDIT: doing some structural changes to the site could also be a good idea (I'm assuming you want to base your translation on community feedback and help, not on an automatic translator). For example you could add a JQuery plugin and then simply place all the translated strings in a dictionary!

**Comment by dkackman** [comment]
Fair points...

> Why don't you use a simple redirect feature? Like the main index page in English and through a localization system you can redirect users to the index page of their language.

Kinda depends on how dynamic the coming changes are going to be. If the site is in for a bunch of additions, styling, design changes etc these would need to be carefully replicated/merged into each locale's copy. If the site is to remain relatively free of change a simple redirect is prolly the way to go.

> For example you could add a JQuery plugin and then simply place all the translated strings in a dictionary!
I would advocate for not reinventing that wheel as Mozilla's framework (and some others) are essentially that.

There are of course pros and cons to any approach.

**Comment by yadavshashwat** [comment]
We can write all the texts (different languages) in the same div/different span class names. 
Can hide the answer based on #key in the address. We can change the key with a simple drop down.

**Comment by alfondotnet** [comment]
I submitted a PR https://github.com/Chia-Network/website/pull/7 for spanish. I'll be sticking around for what is decided

**Comment by dkackman** [comment]
> We can write all the texts (different languages) in the same div/different span class names.
Can hide the answer based on #key in the address. We can change the key with a simple drop down.

Would we not want to just pick it up form the browser locale?

**Comment by dkackman** [comment]
Added a PR with a stub implementation of L20N. May be overkill but for that space between a trivial website and something needing a CMS it is a reasonable solution.
https://github.com/Chia-Network/website/pull/6

**Comment by ghost** [comment]
maybe the translation links should be on top not bottom?

**Comment by menkent33** [comment]
Yo creo que puedo traducir los fundamentos de Chía a español. Si lo veis apropiado contactadme. Listo para aportar.

**Comment by menkent33** [comment]
Sin tecnicismos pero comprensible. No tengo suficiente nivel para transmitir todo el trabajo de criptografía que hay tras Chía pero puedo hacer un texto que comprenda un principiante en criptodivisas.

**Comment by ashadle** [comment]
Hi There, thank you so much for submitting this PR. We are rebranding the website and will have updated copy so I'm going to close out this ticket. Thank you!
