### ISSUE TITLE
Mobile optimisation

### ISSUE THREAD

**Issue by davision** [Chia-Network/website#49]
I am seeing there is quite some issues on a mobile device. Is any of those two branches resolving this? In other way, I would be happy to fix it.

**Comment by ashadle** [comment]
@davision no there isn't, feel free to update the style.css file with your mobile optimizations. Thanks!

**Comment by davision** [comment]
Cool, I've made a pull request #93. This aside, have you been thinking of using any CSS preprocessor and HTML components generator implementation? It will increase readability and ease of development quite much.

**Comment by ashadle** [comment]
@davision I haven't but feel free to create that for us.  I merged your pull request #93 so I'm going to close this issue.
